export const THEME = {
    DANGER_COLOR: '#ee4c33',
    BLUE_COLOR: '#5E91F4',
    WHITE_COLOR: '#FFFFFF',
    ANDROID_STATUS_BAR_COLOR: '#3F75DE',
    GREY_COLOR: '#F7F7F7',
    GREY_ACTIVE_COLOR: '#F0F0F0',
    PADDING_HORIZONTAL: 10
}
